name: "Interconnect CI"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  frontend:
    name: "Frontend"
    runs-on: ubuntu-latest
    container:
      image: node:lts-jod
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        working-directory: "./InterconnectFrontend"
        run: npm ci

      - name: "Build"
        working-directory: "./InterconnectFrontend"
        run: npm run build

      - name: "Run tests"
        working-directory: "./InterconnectFrontend"
        run: npm run test

  backend:
    name: "Backend"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Build"
        working-directory: "./InterconnectBackend"
        run: dotnet build

      - name: "Run tests"
        working-directory: "./InterconnectBackend"
        run: dotnet test

  library:
    name: "Library"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
            apt-get update && apt-get install -y \
                build-essential \
                cmake \
                git \
                libvirt-dev \
                libpcap-dev \
                gdb \
                sudo \
                wget \
                unzip \
                pkg-config \
                libgtest-dev \
                libgmock-dev

      - name: "Build"
        working-directory: "./InterconnectLibrary"
        run: make build

      - name: "Run tests"
        working-directory: "./InterconnectLibrary"
        run: make test